### PR TITLE
Support for implicit discriminants

### PR DESCRIPTION
**Pull request by NighttimeDriver50000**
This allows the use of implicit discriminants in enums, e.g.:

```rust
#[EnumRpr(type = "u8")]
enum Alpha {
    A, // 0
    B, // 1
    C = 5,
    D, // 6
}
```

### CODE REVIEW

**Comment by NighttimeDriver50000** [comment]
Sorry, didn't run the Travis tests. Will debug.

**Comment by NighttimeDriver50000** [comment]
Okay, all fixed, with some new tests for the new behavior as well.

**Comment by dmnsafonov** [comment]
Thanks for your PR!  In the current implementation there is one issue to be considered: if a discriminant was actually forgotten, there is no clue to what happened.  That feature really belongs behind an opt-int flag.  Like:
```
#[EnumRepr(type = "c_int", implicit = true)]
enum En {
    …
}
```

**Comment by NighttimeDriver50000** [comment]
Good point! I've added it.

**Comment by dmnsafonov** [comment]
Thanks!

**Pull request merged**
